### ISSUE TITLE
Suggestion on input bams?

### ISSUE THREAD

**Issue by byemypast** [polyactis/Accucopy#13]
Hi @polyactis, 
First of all, thanks for your great work of Accucopy. It really helps a lot in my low-coverage WGS project.
And I wonder which kind of bam files you would like to suggest as input bams? Such as raw bams after bwa, or sorted bams, or sorted bams with picard-MarkDuplicate procedure?

Thanks,
Junyi

**Comment by polyactis** [comment]
It should be sorted with duplicates marked.

We have updated our documentation
https://www.yfish.org/display/PUB/Accucopy#Accucopy-4.1Inputbamfiles

Thanks for the good question.

--
Prof. Yu S. Huang
Director of Bioinformatics
Drug Discovery and Design Center, State Key Laboratory of Drug Research,
Shanghai Institute of Materia Medica, CAS
http://www.yfish.org/
https://sites.google.com/site/polyactis/

**Comment by byemypast** [comment]
Thank you for your kindly reply and your great work. Have a nice day!
